name: opencv-demo-ogra
version: '0.1'
summary: A little face recognition test
description: |
  A simple OpenCV demo snap, shipping with three python based demos
    - opencv-demo-ogra.eyedetect - demo eye detection
    - opencv-demo-ogra.facedetect - demo face detection
    - opencv-demo-ogra.vidcapture - just a simple video capture demo
  please make sure to run
    sudo snap connect opencv-demo-ogra:camera
  to allow the demo to access your webcam

grade: stable
confinement: strict

apps:
  vidcapture:
    command: vidcapture.py
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$LD_LIBRARY_PATH
    plugs:
      - camera
      - home
      - opengl
      - desktop
      - x11
  facedetect:
    command: facedetect.py
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$LD_LIBRARY_PATH
    plugs:
      - camera
      - home
      - opengl
      - desktop
      - x11
  eyedetect:
    command: eyedetect.py
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/atlas-base/atlas:$LD_LIBRARY_PATH
    plugs:
      - camera
      - home
      - opengl
      - desktop
      - x11

parts:
  opencv:
    plugin: cmake
    source: https://github.com/opencv/opencv.git
    source-tag: 3.0.0
    configflags:
      - -DINSTALL_C_EXAMPLES=ON
      - -DINSTALL_PYTHON_EXAMPLES=ON
      - -DBUILD_EXAMPLES=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av ../../../vidcapture.py $SNAPCRAFT_PART_INSTALL/bin/
      cp -av ../../../facedetect.py $SNAPCRAFT_PART_INSTALL/bin/
      cp -av ../../../eyedetect.py $SNAPCRAFT_PART_INSTALL/bin/
    build-packages:
      - libjpeg-dev
      - libtiff5-dev
      - libjasper-dev
      - libpng12-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      - libgtk2.0-dev
      - libatlas-base-dev
      - gfortran
      - python2.7-dev
      - python3-dev
    stage-packages:
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatlas3-base
      - libatspi2.0-0
      - libavcodec-ffmpeg-extra56
      - libavformat-ffmpeg56
      - libavutil-ffmpeg54
      - libbluray1
      - libboost-filesystem1.58.0
      - libboost-system1.58.0
      - libcairo2
      - libcairo-gobject2
      - libcapnp-0.5.3
      - libcrystalhd3
      - libdatrie1
      - libdc1394-22
      - libepoxy0
      - libexif12
      - libfontconfig1
      - libgdk-pixbuf2.0-0
      - libgme0
      - libgomp1
      - libgphoto2-6
      - libgphoto2-port12
      - libgraphite2-3
      - libgsm1
      - libgtk-3-0
      - libharfbuzz0b
      - libicu55
      - libilmbase12
      - libjasper1
      - libjbig0
      - libjpeg-turbo8
      - libltdl7
      - libmirclient9
      - libmircommon7
      - libmircore1
      - libmirprotobuf3
      - libmodplug1
      - libmp3lame0
      - libnuma1
      - libogg0
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopenexr22
      - libopenjpeg5
      - libopus0
      - liborc-0.4-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libprotobuf-lite9v5
      - libpython2.7
      - libpython3.5
      - libraw1394-11
      - librtmp1
      - libschroedinger-1.0-0
      - libshine3
      - libsnappy1v5
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libswresample-ffmpeg1
      - libswscale-ffmpeg3
      - libthai0
      - libtheora0
      - libtiff5
      - libtwolame0
      - libusb-1.0-0
      - libv4l-0
      - libv4lconvert0
      - libva1
      - libvo-aacenc0
      - libvo-amrwbenc0
      - libvorbis0a
      - libvorbisenc2
      - libvpx3
      - libwavpack1
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libwebp5
      - libx11-6
      - libx264-148
      - libx265-79
      - libxau6
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
      - libxvidcore4
      - libzvbi0
      - python-numpy
